edition = "2018"
unstable_features = true

wrap_comments = true
condense_wildcard_suffixes = true
format_strings = true
merge_imports = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
